server:
  error:
    whitelabel:
      enabled: true
  port: 3030
  
info:
  app:
    version: "@project.version@"
    
logging:
 level:
  web: DEBUG
  org.springframework: INFO
  org.springframework.security: DEBUG
  com.persons.finder: INFO
 pattern:
  console: "%date %-5.5level %4.4thread [%25.25file:%3.3line] %X{breadCrumbId} - %msg%n"
  file: "${spring.application.name} %date %-5.5level %4.4thread [%25.25file:%3.3line] %X{breadCrumbId} - %msg%n"
  
spring:
 application:
    name: persons.finder-4j
 security:
#  user:
#   password: senha   
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    #url: jdbc:h2:mem:titherdb
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: senha   
   
logging.file: /opt/log/persons-finder-4j-service.log

